In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Ambon,ID,2022-07-12 00:09:43,-3.6954,128.1814,75.34,94,40,5.75
1,1,Nikolskoye,RU,2022-07-12 00:09:43,59.7035,30.7861,64.29,98,100,7.65
2,2,Bredasdorp,ZA,2022-07-12 00:09:03,-34.5322,20.0403,48.78,83,1,5.91
3,3,Puri,IN,2022-07-12 00:06:25,19.8000,85.8500,81.12,82,97,2.66
4,4,Te Anau,NZ,2022-07-12 00:09:43,-45.4167,167.7167,38.82,69,100,2.71

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [6]:
# 1. Assign the locations to an array of latitude and longitude pairs.
locations = [latitude, longitude]

# 2. Assign the weights variable to some values..

temperatures = # an array of length equal to the locations array length

# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure()
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)

# 5. Add the heatmap layer.
fig.add_layer(heatmap_layer)
# 6. Call the figure to plot the data.
fig

# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

SyntaxError: invalid syntax (2505995157.py, line 6)